Css canvas medical- David Gonzalez
David-Gonzalez11/rc0522-code-solutions pull request #21
Opened 2022-05-16 01:40 UTC by David-Gonzalez11

https://user-images.githubusercontent.com/24907191/168505789-9096937d-2bd1-42ba-82ab-1d0ba4907e97.mov

2022-05-16 17:27 UTC, Zhiwutian requested changes
Looking solid overall! A few things to look at:
1. Make sure to remove excess whitespace from the code.
2. Make sure the widths for your column classes match the names, for example 2/3 should indicate 2/3 of a rows width. 
3. some of the text spacing needs to be adjusted. for example the address in the footer. Make sure to check the text spacing of the example.

Keep up the good work!

2022-05-16 17:27 UTC, Zhiwutian commented on css-canvas-medical/index.html
> +
make sure to remove any whitespace in the code like this.

2022-05-17 00:03 UTC, David-Gonzalez11 commented
https://user-images.githubusercontent.com/24907191/168701303-bd4ece74-d701-445d-ac27-03642b5eb0b0.mov

2022-05-17 00:14 UTC, Zhiwutian approved these changes
👍🏼

2022-05-17 16:45 UTC, merged